//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAchievementViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamAchievementViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the achievement list. Please wait and try again later.
        /// </summary>
        public static string AchievementListFailed {
            get {
                return ResourceManager.GetString("AchievementListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The achievement list has been successfully received.
        /// </summary>
        public static string AchievementListRetrieved {
            get {
                return ResourceManager.GetString("AchievementListRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LOGIN.
        /// </summary>
        public static string AuthPage {
            get {
                return ResourceManager.GetString("AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ALL CLOSEST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string ClosestAllPage {
            get {
                return ResourceManager.GetString("ClosestAllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CLOSEST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string ClosestPage {
            get {
                return ResourceManager.GetString("ClosestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your Steam ID.
        /// </summary>
        public static string EnterSteamID {
            get {
                return ResourceManager.GetString("EnterSteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get the game list. Please wait and try again later.
        /// </summary>
        public static string GameListFailed {
            get {
                return ResourceManager.GetString("GameListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The game list has been successfully received.
        /// </summary>
        public static string GameListRetrieved {
            get {
                return ResourceManager.GetString("GameListRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LAST
        /// ACHIEVED.
        /// </summary>
        public static string LastAchievedPage {
            get {
                return ResourceManager.GetString("LastAchievedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MAIN.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to get profile information. Please wait and try again later.
        /// </summary>
        public static string ProfileDataFailed {
            get {
                return ResourceManager.GetString("ProfileDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile data has been successfully retrieved.
        /// </summary>
        public static string ProfileDataRetrieved {
            get {
                return ResourceManager.GetString("ProfileDataRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RAREST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string RarestPage {
            get {
                return ResourceManager.GetString("RarestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Results have been saved successfully.
        /// </summary>
        public static string ResultSaved {
            get {
                return ResourceManager.GetString("ResultSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saving the results.
        /// </summary>
        public static string ResultSaving {
            get {
                return ResourceManager.GetString("ResultSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieving the achievement list.
        /// </summary>
        public static string RetrievingAchievementList {
            get {
                return ResourceManager.GetString("RetrievingAchievementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieving the game list.
        /// </summary>
        public static string RetrievingGameList {
            get {
                return ResourceManager.GetString("RetrievingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retrieving profile data.
        /// </summary>
        public static string RetrievingProfileData {
            get {
                return ResourceManager.GetString("RetrievingProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SETTINGS.
        /// </summary>
        public static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
    }
}
