//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamAchievementViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteamAchievementViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the achievement list. Please wait and try again later.
        /// </summary>
        public static string AchievementListFailed {
            get {
                return ResourceManager.GetString("AchievementListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The achievement list has been successfully received.
        /// </summary>
        public static string AchievementListRetrieved {
            get {
                return ResourceManager.GetString("AchievementListRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGIN.
        /// </summary>
        public static string AuthPage {
            get {
                return ResourceManager.GetString("AuthPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL CLOSEST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string ClosestAllPage {
            get {
                return ResourceManager.GetString("ClosestAllPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSEST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string ClosestPage {
            get {
                return ResourceManager.GetString("ClosestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETED GAMES.
        /// </summary>
        public static string CompletedGamesPage {
            get {
                return ResourceManager.GetString("CompletedGamesPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EASIEST GAMES
        /// TO 100%.
        /// </summary>
        public static string EasiestGamesToCompletePage {
            get {
                return ResourceManager.GetString("EasiestGamesToCompletePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Steam ID.
        /// </summary>
        public static string EnterSteamID {
            get {
                return ResourceManager.GetString("EnterSteamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the game list. Please wait and try again later.
        /// </summary>
        public static string GameListFailed {
            get {
                return ResourceManager.GetString("GameListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game list has been successfully received.
        /// </summary>
        public static string GameListRetrieved {
            get {
                return ResourceManager.GetString("GameListRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST
        /// ACHIEVED.
        /// </summary>
        public static string LastAchievedPage {
            get {
                return ResourceManager.GetString("LastAchievedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get profile information. Please wait and try again later.
        /// </summary>
        public static string ProfileDataFailed {
            get {
                return ResourceManager.GetString("ProfileDataFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile data has been successfully retrieved.
        /// </summary>
        public static string ProfileDataRetrieved {
            get {
                return ResourceManager.GetString("ProfileDataRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAREST
        /// ACHIEVEMENTS.
        /// </summary>
        public static string RarestPage {
            get {
                return ResourceManager.GetString("RarestPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results have been saved successfully.
        /// </summary>
        public static string ResultSaved {
            get {
                return ResourceManager.GetString("ResultSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving the results.
        /// </summary>
        public static string ResultSaving {
            get {
                return ResourceManager.GetString("ResultSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the achievement list.
        /// </summary>
        public static string RetrievingAchievementList {
            get {
                return ResourceManager.GetString("RetrievingAchievementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the game list.
        /// </summary>
        public static string RetrievingGameList {
            get {
                return ResourceManager.GetString("RetrievingGameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving profile data.
        /// </summary>
        public static string RetrievingProfileData {
            get {
                return ResourceManager.GetString("RetrievingProfileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsPage {
            get {
                return ResourceManager.GetString("SettingsPage", resourceCulture);
            }
        }
    }
}
